[theme]
theme = "space-villain"
[icons]
icons = "awesome5"

#[[block]]
#block = "music"
#hide_when_empty = true
#marquee = false
#on_click = "playerctl play-pause"
#dynamic_width = true

[[block]]
alert = 10.0
block = "disk_space"
info_type = "available"
interval = 20
path = "/"
warning = 20.0
format = "$icon $available/$used"

#[[block]]
#block = "memory"
#format_mem = " $mem_total/$mem_total_used "
#icons = true

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

#[[block]]
#block = "cpu"
#format = " $icon $utilization "

[[block]]
block = "load"
format = " $1m $5m $15m "
interval = 2

[[block]]
block = "net"
device = "wlp0s20u7"
#format = "{signal_strength} {speed_down;K*b} {graph_down;K}"
#format = "{ssid} {signal_strength}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 10

#[[block]]
#block = "time"
#format = " $%a$%d/$%m$%R "
#interval = 60

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

#[[block]]
#block = "custom"
#command = "echo '\uF011'"
#interval = 999999
#on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"

